     <p>Mata Kuliah  (isi sendiri)</p>   
<html lang="id">
<Kepala>
 <meta charset= "UTF-8">
 <judul> Web Pertama Saya</judul> 
</kepala>
<tubuh>

 <h1> Selamat Datang di Web Saya</h1> 
   <p> Web ini dibuat menggunakan HTML.</p>   

 <p>Nama Rahmy Intan</p> Rahmy Intan</p>
    <p>Mata Kuliah  (isi sendiri)</p>(isi sendiri)</p>  

</tubuh>
</html>
